/*
 * Copyright (c) 2026 Touchlab.
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */

package co.touchlab.kmmbridge.spm

/**
 * Generates Package.swift content from SPM module metadata.
 * Shared by the plugin and tests.
 */
internal object PackageSwiftGenerator {

    internal val versionComparator = Comparator<String> { v1, v2 ->
        val parts1 = v1.split(".").mapNotNull { it.toIntOrNull() }
        val parts2 = v2.split(".").mapNotNull { it.toIntOrNull() }
        val maxLen = maxOf(parts1.size, parts2.size)
        for (i in 0 until maxLen) {
            val p1 = parts1.getOrElse(i) { 0 }
            val p2 = parts2.getOrElse(i) { 0 }
            if (p1 != p2) return@Comparator p1.compareTo(p2)
        }
        0
    }

    /**
     * Resolve the Swift tools version to use.
     * Uses the maximum version from all modules, or the configured default.
     */
    internal fun resolveSwiftToolsVersion(modules: List<SpmModuleMetadata>, defaultVersion: String): String {
        val versions = modules.map { it.swiftToolsVersion }.filter { it.isNotBlank() }
        return if (versions.isNotEmpty()) {
            versions.maxWithOrNull(versionComparator) ?: defaultVersion
        } else {
            defaultVersion
        }
    }

    /**
     * Resolve platforms by taking the maximum version for each platform across all modules.
     */
    internal fun resolvePlatforms(modules: List<SpmModuleMetadata>): Map<String, String> {
        val platformVersions = mutableMapOf<String, MutableList<String>>()
        modules.forEach { module ->
            module.platforms.forEach { (platform, version) ->
                platformVersions.getOrPut(platform) { mutableListOf() }.add(version)
            }
        }
        return platformVersions.mapValues { (_, versions) ->
            versions.maxWithOrNull(versionComparator) ?: versions.first()
        }
    }

    /**
     * Generate the complete Package.swift content for a remote (published) package.
     */
    internal fun generate(packageName: String, swiftToolsVersion: String, modules: List<SpmModuleMetadata>): String {
        val platforms = resolvePlatforms(modules)
        val platformsString = platforms.entries
            .sortedBy { it.key }
            .joinToString(",\n        ") { (platform, version) ->
                ".$platform(.v$version)"
            }

        val productsString = modules
            .sortedBy { it.frameworkName }
            .joinToString(",\n        ") { module ->
                ".library(name: \"${module.frameworkName}\", targets: [\"${module.frameworkName}\"])"
            }

        val targetsString = modules
            .sortedBy { it.frameworkName }
            .joinToString(",\n        ") { module ->
                """.binaryTarget(
            name: "${module.frameworkName}",
            url: "${module.url}",
            checksum: "${module.checksum}"
        )"""
            }

        return """// swift-tools-version:$swiftToolsVersion
// Generated by KMMBridge - DO NOT EDIT MANUALLY
// https://github.com/touchlab/KMMBridge
import PackageDescription

let package = Package(
    name: "$packageName",
    platforms: [
        $platformsString
    ],
    products: [
        $productsString
    ],
    targets: [
        $targetsString
    ]
)
"""
    }
}
