/*
 * Copyright (c) 2024 Touchlab.
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */

package co.touchlab.kmmbridge.spm

/**
 * Generates Package.swift content from module metadata.
 *
 * This class is intentionally free of Gradle dependencies so it can be unit-tested
 * without a Gradle project context.
 */
internal class PackageSwiftGenerator {

    internal val versionComparator = Comparator<String> { v1, v2 ->
        val parts1 = v1.split(".").mapNotNull { it.toIntOrNull() }
        val parts2 = v2.split(".").mapNotNull { it.toIntOrNull() }
        val maxLen = maxOf(parts1.size, parts2.size)
        for (i in 0 until maxLen) {
            val p1 = parts1.getOrElse(i) { 0 }
            val p2 = parts2.getOrElse(i) { 0 }
            if (p1 != p2) return@Comparator p1.compareTo(p2)
        }
        0
    }

    /**
     * Resolve the Swift tools version to use.
     * Uses the maximum version from all modules, or the configured default.
     */
    fun resolveSwiftToolsVersion(modules: List<SpmModuleMetadata>, defaultVersion: String): String {
        val versions = modules.map { it.swiftToolsVersion }.filter { it.isNotBlank() }
        return if (versions.isNotEmpty()) {
            versions.maxWithOrNull(versionComparator) ?: defaultVersion
        } else {
            defaultVersion
        }
    }

    /**
     * Resolve platforms by taking the maximum version for each platform across all modules.
     */
    fun resolvePlatforms(modules: List<SpmModuleMetadata>): Map<String, String> {
        val platformVersions = mutableMapOf<String, MutableList<String>>()

        modules.forEach { module ->
            module.platforms.forEach { (platform, version) ->
                platformVersions.getOrPut(platform) { mutableListOf() }.add(version)
            }
        }

        return platformVersions.mapValues { (_, versions) ->
            versions.maxWithOrNull(versionComparator) ?: versions.first()
        }
    }

    /**
     * Generate the complete Package.swift content for remote (published) modules.
     */
    fun generatePackageSwift(packageName: String, swiftToolsVersion: String, modules: List<SpmModuleMetadata>): String {
        val platforms = resolvePlatforms(modules)
        val platformsString = formatPlatforms(platforms)

        val productsString = modules
            .sortedBy { it.frameworkName }
            .joinToString(",\n        ") { module ->
                val name = escapeSwiftString(module.frameworkName)
                ".library(name: \"$name\", targets: [\"$name\"])"
            }

        val targetsString = modules
            .sortedBy { it.frameworkName }
            .joinToString(",\n        ") { module ->
                val name = escapeSwiftString(module.frameworkName)
                val url = escapeSwiftString(module.url)
                val checksum = escapeSwiftString(module.checksum)
                """.binaryTarget(
            name: "$name",
            url: "$url",
            checksum: "$checksum"
        )"""
            }

        return """// swift-tools-version:$swiftToolsVersion
// Generated by KMMBridge - DO NOT EDIT MANUALLY
// https://github.com/touchlab/KMMBridge
import PackageDescription

let package = Package(
    name: "${escapeSwiftString(packageName)}",
    platforms: [
        $platformsString
    ],
    products: [
        $productsString
    ],
    targets: [
        $targetsString
    ]
)
"""
    }

    /**
     * Generate Package.swift content with local paths for development.
     */
    fun generateLocalPackageSwift(
        packageName: String,
        swiftToolsVersion: String,
        modules: List<LocalModuleInfo>,
    ): String {
        val platforms = modules.flatMap { it.platforms.entries }
            .groupBy({ it.key }, { it.value })
            .mapValues { (_, versions) -> versions.maxWithOrNull(versionComparator) ?: versions.first() }

        val platformsString = formatPlatforms(platforms)

        val productsString = modules
            .sortedBy { it.frameworkName }
            .joinToString(",\n        ") { module ->
                val name = escapeSwiftString(module.frameworkName)
                ".library(name: \"$name\", targets: [\"$name\"])"
            }

        val targetsString = modules
            .sortedBy { it.frameworkName }
            .joinToString(",\n        ") { module ->
                val name = escapeSwiftString(module.frameworkName)
                val path = escapeSwiftString(module.localPath)
                """.binaryTarget(
            name: "$name",
            path: "$path"
        )"""
            }

        return """// swift-tools-version:$swiftToolsVersion
// Generated by KMMBridge (LOCAL DEV) - DO NOT COMMIT
// https://github.com/touchlab/KMMBridge
import PackageDescription

let package = Package(
    name: "${escapeSwiftString(packageName)}",
    platforms: [
        $platformsString
    ],
    products: [
        $productsString
    ],
    targets: [
        $targetsString
    ]
)
"""
    }

    private fun formatPlatforms(platforms: Map<String, String>): String =
        platforms.entries
            .sortedBy { it.key }
            .joinToString(",\n        ") { (platform, version) ->
                ".$platform(.v$version)"
            }

    /**
     * Data class for local module info (used for spmDevBuildAll).
     */
    data class LocalModuleInfo(val frameworkName: String, val localPath: String, val platforms: Map<String, String>)

    companion object {
        /**
         * Escape a string for safe inclusion in a Swift string literal.
         */
        fun escapeSwiftString(value: String): String =
            value.replace("\\", "\\\\").replace("\"", "\\\"")
    }
}
