name: "Integration Test"

on: 
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "website/**"
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "website/**"
  workflow_dispatch:
      
jobs:
  build:
    runs-on: macos-12
    env:
      GITHUB_PUBLISH_USER: "Touchlab-Bot"
    strategy:
      matrix:
        sample: [ KmmBridgeIntegrationTest, KmmBridgeIntegrationTest-GithubReleases, KmmBridgeIntegrationTest-MavenGHPackages-GHReleaseVersions ]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "11"
      
      - name: "Checkout sample"
        uses: actions/checkout@v3
        with:
          repository: "touchlab/${{ matrix.sample }}"
          ref: main
          path: "build/${{ matrix.sample }}"

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
        with:
          min-wrapper-count: 2 # Validating both the local wrapper and the one in the cloned sample

      - name: Apply SSH Key
        uses: webfactory/ssh-agent@836c84ec59a0e7bc0eabc79988384eb567561ee2 # v0.7.0
        with:
          ssh-private-key: |
            ${{ secrets.PODSPEC_SSH_KEY }}
            ${{ secrets.INTEGRATION_TEST_MAVEN_PUBLISH_SSH_KEY }}
            ${{ secrets.INTEGRATION_TEST_GITHUB_RELEASES_SSH_KEY }}
            ${{ secrets.INTEGRATION_TEST_MavenGHPackages_GHReleaseVersions }}

      - uses: extractions/netrc@938ddbfb73b4efee33e57db13aba434b35af2f93 # v1
        with:
          machine: api.github.com
          username: ${{ env.GITHUB_PUBLISH_USER }}
          password: ${{ secrets.INTEGRATION_TEST_GITHUB_TOKEN }}

      - uses: extractions/netrc@938ddbfb73b4efee33e57db13aba434b35af2f93 # v1
        with:
          machine: maven.pkg.github.com
          username: ${{ env.GITHUB_PUBLISH_USER }}
          password: ${{ secrets.INTEGRATION_TEST_GITHUB_TOKEN }}

      - name: Cache build tooling
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.konan
          key: ${{ runner.os }}-v4-${{ hashFiles('*.gradle.kts') }}

      # TODO can we cache this so it only runs once instead of running for every test case?
      - name: Local publish plugin
        run: |
          ./gradlew publishToMavenLocal -PRELEASE_SIGNING_ENABLED=false -PVERSION_NAME=999

      - name: Publish shared
        run: |
          cd build/${{ matrix.sample }}
          ./gradlew kmmBridgePublish -PGITHUB_PUBLISH_TOKEN=${{ secrets.INTEGRATION_TEST_GITHUB_TOKEN }} -PGITHUB_REPO=touchlab/${{ matrix.sample }} -PGITHUB_PUBLISH_USER=${{ env.GITHUB_PUBLISH_USER }} --no-daemon --stacktrace
        env:
          GRADLE_OPTS: -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=512m"

      - name: Build SPM Sample
        run: |
          cd build/${{ matrix.sample }}/ios-spm
          xcodebuild -configuration Debug -scheme KmmBridgeIntegrationTestSpm -sdk iphonesimulator 

      - name: Build Cocoapods Sample
        run: |
          cd build/${{ matrix.sample }}/ios-cocoapods
          pod install
          xcodebuild -workspace KmmBridgeIntegrationTestCocoapods.xcworkspace -configuration Debug -scheme KmmBridgeIntegrationTestCocoapods -sdk iphonesimulator
