name: "Integration Test"

on: 
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "website/**"
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "website/**"
  workflow_dispatch:
      
jobs:
  build:
    runs-on: macos-12
    strategy:
      matrix:
        sample: [touchlab-lab/KmmBridgeIntegrationTest] # TODO add other samples here.

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "11"
      
      - name: "Checkout sample"
        uses: actions/checkout@v3
        with:
          repository: "${{ matrix.sample }}"
          ref: main
          path: "build/${{ matrix.sample }}"
          token: ${{ github.token }}

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
        with:
          min-wrapper-count: 2 # Validating both the local wrapper and the one in the cloned sample

      - name: Apply SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.PODSPEC_SSH_KEY }}

      - uses: extractions/netrc@v1
        with:
          machine: api.github.com
          username: "cirunner"
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache build tooling
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.konan
          key: ${{ runner.os }}-v4-${{ hashFiles('*.gradle.kts') }}

      - name: Local publish plugin
        run: |
          ./gradlew publishToMavenLocal -PRELEASE_SIGNING_ENABLED=false -PVERSION_NAME=999
          
      - name: Run sample tests
        run: |
          cd build/${{ matrix.sample }}
          ./run_tests.sh
        
        
        
